pushing code python-java prov9

diff --git a/.github/workflows/ci-cd-local.yml b/.github/workflows/ci-cd-local.yml
--- a/.github/workflows/ci-cd-local.yml
+++ b/.github/workflows/ci-cd-local.yml
@@ -29,7 +29,7 @@ jobs:
       # Build Docker Images (multi-stage Dockerfile handles JAR packaging)
       - name: Build Docker Images
         run: |
-          docker build -t java-app:local java-app
+        #  docker build -t java-app:local java-app
           docker build -t python-app:local python-app
 
   local-run:
@@ -46,8 +46,8 @@ jobs:
       - name: Verify Python Service
         run: curl --fail http://localhost:8000 || echo "Python app not responding"
 
-      - name: Verify Java Service
-        run: curl --fail http://localhost:9090 || echo "Java app not responding"
+      # - name: Verify Java Service
+      #   run: curl --fail http://localhost:9090 || echo "Java app not responding"
 
   # /* terraform-validate:
   #   needs: build-test
